package schoolapp;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.*;
import java.sql.*;
import java.sql.Statement;
import java.sql.ResultSet;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bhush
 */
public class Tearcher_Window extends javax.swing.JFrame {

    /**
     * Creates new form Tearcher_Window
     */
    public Tearcher_Window() {
        initComponents();
        //getMysqlConnection();
        FillTable();
    }
    
    public Connection getMysqlConnection(){
        Connection conn = null;
    try{
        Class.forName("com.mysql.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/prajakta","root","@PrajaktaMysql3");
       // JOptionPane.showMessageDialog(null,"Connection is Successfull....");
        return conn;
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error"+e);
        return null;
    }
   
    }
    //show / Add the data to Table
    public  ArrayList <Teacher_Bean> getAllTeacherData(){
    ArrayList<Teacher_Bean> al =null;
    al = new ArrayList<Teacher_Bean>();
    
    try{
    Connection conn = getMysqlConnection();
    String qry = "Select * from teachers";
    Statement st = conn.createStatement();
    ResultSet rs = st.executeQuery(qry);
    Teacher_Bean teacher;
    while(rs.next()){
    teacher = new Teacher_Bean(Integer.parseInt(rs.getString(1)),rs.getString("name"),Float.parseFloat(rs.getString(3)),rs.getString(4),rs.getString("address"),rs.getString(6));
    al.add(teacher);
    //return al;
    }
   
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error in getAllTeacherData"+e);
        return al;
    }
        return al;
    }
    
    public void FillTable(){
    ArrayList<Teacher_Bean> al = getAllTeacherData();
    DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
    model.setRowCount(0);
    Object[] row = new Object[6];
    for(int i = 0; i< al.size();i++){
    row[0]=al.get(i).getId();
    row[1]=al.get(i).getName();
    row[2]=al.get(i).getSalary();
    row[3]=al.get(i).getDob();
    row[4]=al.get(i).getAddress();
    row[5]=al.get(i).getSubject();
    model.addRow(row);
    }
    }
    
    public void showItemToFieldsTeacher(int index){
    jTextField_id.setText(Integer.toString(getAllTeacherData().get(index).getId()));
    jTextField_name.setText(getAllTeacherData().get(index).getName());
    jTextField_salary.setText(Float.toString(getAllTeacherData().get(index).getSalary()));
    try{
    java.util.Date dob = null;
    dob = new SimpleDateFormat("dd-MM-yyyy").parse((String)getAllTeacherData().get(index).getDob());
    jDateChooserDOB.setDate(dob);
    }catch(Exception e){
    JOptionPane.showMessageDialog(null,"Error showItemToFieldsTeacher() " +e);
    }
     jTextAreaAddress.setText(getAllTeacherData().get(index).getAddress());
     jTextFieldSubject.setText(getAllTeacherData().get(index).getSubject());
     
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();
        jTextField_name = new javax.swing.JTextField();
        jTextField_salary = new javax.swing.JTextField();
        jDateChooserDOB = new com.toedter.calendar.JDateChooser();
        jTextFieldSubject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jButton1_clear = new javax.swing.JButton();
        jButton2_save = new javax.swing.JButton();
        jButton3_edit = new javax.swing.JButton();
        jButton4_delete = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Search = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setText("Tearher ID:");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel2.setText("Name:");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel3.setText("Salary:");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setText("Date Of Birth:");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel5.setText("Address:");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel6.setText("Subject:");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("CSMSS Chh Shahu College of Engineering");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Tearcher Information");

        jTextField_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_nameActionPerformed(evt);
            }
        });

        jTextField_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_salaryActionPerformed(evt);
            }
        });

        jDateChooserDOB.setDateFormatString("dd-MM-yyyy");

        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setRows(5);
        jScrollPane1.setViewportView(jTextAreaAddress);

        jButton1_clear.setBackground(new java.awt.Color(204, 204, 204));
        jButton1_clear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1_clear.setForeground(new java.awt.Color(0, 0, 255));
        jButton1_clear.setText("New / Clear");
        jButton1_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_clearActionPerformed(evt);
            }
        });

        jButton2_save.setBackground(new java.awt.Color(204, 204, 204));
        jButton2_save.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2_save.setForeground(new java.awt.Color(0, 0, 255));
        jButton2_save.setText("Save / Insert");
        jButton2_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_saveActionPerformed(evt);
            }
        });

        jButton3_edit.setBackground(new java.awt.Color(204, 204, 204));
        jButton3_edit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3_edit.setForeground(new java.awt.Color(0, 0, 255));
        jButton3_edit.setText("Update / Edit");
        jButton3_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_editActionPerformed(evt);
            }
        });

        jButton4_delete.setBackground(new java.awt.Color(204, 204, 204));
        jButton4_delete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4_delete.setForeground(new java.awt.Color(0, 0, 255));
        jButton4_delete.setText("Delete / Remove");
        jButton4_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4_deleteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel7.setText("Search Name:");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextField_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SearchActionPerformed(evt);
            }
        });
        jTextField_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_SearchKeyReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Teacher ID", "Name", "Salary", "Date Of Birth", "Address", "Subject"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Teacher ID");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Name");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Salary");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Date Of Birth");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Address");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("Subject");
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(184, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(604, 604, 604))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(268, 268, 268)
                                .addComponent(jDateChooserDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1_clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2_save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3_edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4_delete, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addGap(140, 140, 140))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(450, 450, 450))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField_Search)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldSubject)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE))
                .addGap(347, 347, 347))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(jButton1_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton2_save, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jDateChooserDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton3_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jLabel6))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_salaryActionPerformed

    private void jTextField_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nameActionPerformed

    private void jTextField_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SearchActionPerformed
//to save / insert the record
    private void jButton2_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_saveActionPerformed
        // TODO add your handling code here:
         if(jTextField_id.getText().toString().equals("")|| jTextField_name.getText().toString().equals("")
                 ||jTextField_salary.getText().toString().equals("")||jTextAreaAddress.getText().toString().equals("")
                 ||jTextFieldSubject.getText().toString().equals("")){
        JOptionPane.showMessageDialog(null,"All Field Are Compulsory");
        }else{
             try{
             Connection conn = getMysqlConnection();
             String qry = "insert into teachers(id,name,salary,dob,address,subject) values(?,?,?,?,?,?)";
             PreparedStatement ps = conn.prepareStatement(qry);
             
             ps.setInt(1,Integer.parseInt(jTextField_id.getText().toString()));
             ps.setString(2,jTextField_name.getText().toString());
             ps.setFloat(3,Float.parseFloat(jTextField_salary.getText().toString()));
             
             SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
             String dob1 = sdf.format(jDateChooserDOB.getDate());
             ps.setString(4,dob1);
             
             ps.setString(5,jTextAreaAddress.getText().toString());
             ps.setString(6,jTextFieldSubject.getText().toString());
             
             int result = ps.executeUpdate();
              FillTable();
             if(result >= 1){
              JOptionPane.showMessageDialog(null,result+"Teacher Record Save Successfully....");
             }else{
                 JOptionPane.showMessageDialog(null,result+"Teacher Record Fail Try Again....");
             }
              if(ps != null){
                  ps.close();
        }
             if(conn!=null){
             conn.close();
             }
             }catch(Exception e){
                 JOptionPane.showMessageDialog(null,"Eorro in Insert"+e);
                 
             }
             //clear the field
        jTextField_id.setText("");
        jTextField_name.setText("");
        jTextField_salary.setText("");
        jTextAreaAddress.setText("");
        jTextFieldSubject.setText("");
        }
        
    }//GEN-LAST:event_jButton2_saveActionPerformed

    private void jButton1_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_clearActionPerformed
        // TODO add your handling code here:
        jTextField_id.setText("");
        jTextField_name.setText("");
        jTextField_salary.setText("");
        jTextAreaAddress.setText("");
        jTextFieldSubject.setText("");
    }//GEN-LAST:event_jButton1_clearActionPerformed
//upadate / edit the record
    private void jButton3_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_editActionPerformed

        // TODO add your handling code here:
         if(jTextField_id.getText().toString().equals("")|| jTextField_name.getText().toString().equals("")
                 ||jTextField_salary.getText().toString().equals("")||jTextAreaAddress.getText().toString().equals("")
                 ||jTextFieldSubject.getText().toString().equals("")){
        JOptionPane.showMessageDialog(null,"All Field Are Compulsory");
        }else{
             try{
             Connection conn = getMysqlConnection();
             String qry = "update teachers set name = ?,salary = ?,dob = ?,address = ?,subject = ? where id = ?";
             PreparedStatement ps = conn.prepareStatement(qry);
             
            
             ps.setString(1,jTextField_name.getText().toString());
             ps.setFloat(2,Float.parseFloat(jTextField_salary.getText().toString()));
             
             SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
             String dob1 = sdf.format(jDateChooserDOB.getDate());
             ps.setString(3,dob1);
             
             ps.setString(4,jTextAreaAddress.getText().toString());
             ps.setString(5,jTextFieldSubject.getText().toString());
             
              ps.setInt(6,Integer.parseInt(jTextField_id.getText().toString()));
             
             int result = ps.executeUpdate();
              FillTable();
             if(result >= 1){
              JOptionPane.showMessageDialog(null,result+"Teacher Record Updated Successfully "+jTextField_name.getText().toString());
             }else{
                 JOptionPane.showMessageDialog(null,result+"Teacher Record Fail to Update Try Again....");
             }
              if(ps != null){
                 ps.close();
        }
              if(conn!=null){
             conn.close();
             }
             }catch(Exception e){
                 JOptionPane.showMessageDialog(null,"Error in Update"+e);
                 
             }
             //clear the field
        jTextField_id.setText("");
        jTextField_name.setText("");
        jTextField_salary.setText("");
        jTextAreaAddress.setText("");
        jTextFieldSubject.setText("");
        }
        
    }//GEN-LAST:event_jButton3_editActionPerformed
//Delete the record
    private void jButton4_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4_deleteActionPerformed
        // TODO add your handling code here:
        if(jTextField_id.getText().toString().equals("")){
        JOptionPane.showMessageDialog(null,"All Field Are Compulsory");
        }else{
             try{
             Connection conn = getMysqlConnection();
             String qry = "delete from teachers where id = ?";
             PreparedStatement ps = conn.prepareStatement(qry);
             
             ps.setInt(1,Integer.parseInt(jTextField_id.getText().toString()));
             
             int result = ps.executeUpdate();
              FillTable();
             if(result >= 1){
              JOptionPane.showMessageDialog(null,result+"Teacher Record Deleted Successfully "+jTextField_id.getText().toString());
             }else{
                 JOptionPane.showMessageDialog(null,result+"Teacher Record Fail to Delete Try Again....");
             }
              if(ps != null){
                  ps.close();
        }
             if(conn!=null){
             conn.close();
             }
             
             }catch(Exception e){
                 JOptionPane.showMessageDialog(null," error in Delete"+e);
                 
             }
             //clear the field
        jTextField_id.setText("");
        jTextField_name.setText("");
        jTextField_salary.setText("");
        jTextAreaAddress.setText("");
        jTextFieldSubject.setText("");
        }
    }//GEN-LAST:event_jButton4_deleteActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int ind = jTable1.getSelectedRow();
        showItemToFieldsTeacher(ind);
    }//GEN-LAST:event_jTable1MouseClicked
//Search in table
    private void jTextField_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchKeyReleased
        // TODO add your handling code here:
        ArrayList<Teacher_Bean> al = null;
        al = new ArrayList<Teacher_Bean>();
        String val = jTextField_Search.getText().toString();
        
        try{
        Connection conn = getMysqlConnection();
        String qry = "select * from teachers where name like '%"+val+"%'";
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(qry);
        Teacher_Bean teacher;
        while(rs.next()){
    teacher = new Teacher_Bean(Integer.parseInt(rs.getString(1)),rs.getString("name"),Float.parseFloat(rs.getString(3)),rs.getString(4),rs.getString("address"),rs.getString(6));
    al.add(teacher);
        }
        if(st != null){
        st.close();
        }
        if(conn != null){
        conn.close();
        }
         DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
    model.setRowCount(0);
    Object[] row = new Object[6];
    for(int i = 0; i< al.size();i++){
    row[0]=al.get(i).getId();
    row[1]=al.get(i).getName();
    row[2]=al.get(i).getSalary();
    row[3]=al.get(i).getDob();
    row[4]=al.get(i).getAddress();
    row[5]=al.get(i).getSubject();
    model.addRow(row);
    }
     
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Error in Search " +e);
        }
    }//GEN-LAST:event_jTextField_SearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tearcher_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tearcher_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tearcher_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tearcher_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tearcher_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_clear;
    private javax.swing.JButton jButton2_save;
    private javax.swing.JButton jButton3_edit;
    private javax.swing.JButton jButton4_delete;
    private com.toedter.calendar.JDateChooser jDateChooserDOB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JTextField jTextFieldSubject;
    private javax.swing.JTextField jTextField_Search;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_salary;
    // End of variables declaration//GEN-END:variables
}
